Ticket 9 post comment
adnaani/Adnaans-NC-GAMES-FRONT-END pull request #6
Opened 2022-06-16 14:53 UTC by adnaani

9. Post a new comment to an existing review

2022-06-16 15:15 UTC, leekli requested changes
Hi Adnaan, a good start to the ticket however there are a few things to note/changes requested:

* The comment form requires me to enter a username. There should either be a hard coded user already set up for this, or have a 'logged in' user if this has been created (think about that useContext we covered last week on how to achieve this). We shouldn't expect the user to have to manually type in their username to submit a comment, there's also nothing to tell the user which usernames they can use if they were to type a username in. This app is an app you will be showing to prospective employers, so you want to make it as easy as possible for them to navigate it and add comments.
* I can see it doesn't allow me submit a new comment if the comment box is empty, but it doesn't give me, as a user, any error message to tell me the field is required... as a user it just looks like it doesn't work when I try to submit an empty comment. Have a look at using something like the 'required' tag in the <textarea> element.
* On the new comment form, the 'write' button doesn't seem as obvious to me, as a user, as it could be. Can you maybe change this to 'submit', or 'post'. I'd also look into turning it into something which more visually represents a button, currently it just looks like text and isn't obvious to me as a user as being something i should click.
* When I submitted a new comment, the Chrome console presented me with an error message about each child element not having a unique key prop - take a look.

Please review these changes, implement them and then submit a new pull request once complete.

2022-06-17 11:22 UTC, Rosem10 requested changes
All in all really good. The only change I'd like you to make is the behaviour once the user has posted a comment. Currently, the user gets visual feedback in the form of the comment being posted at the bottom of the list - however if there are a lot of comments, the user would need to scroll right to the bottom for confirmation, which isn't great UX. I'd suggest either having some sort of message/ alert pop up once the comment is posted, or having the comment appear at the top of the list, so the user gets instant gratification.

2022-06-17 11:22 UTC, Rosem10 commented on src/components/Navbar/Navbar.jsx
> +  console.log(loggedUser);
Please remove!

2022-06-17 11:22 UTC, Rosem10 commented on src/utils/dateCalculator.js
> +  switch (true) {
This is lovely.

2022-06-17 14:12 UTC, merged